import { BadgeDollarSign, CreditCard } from 'lucide-react'

export const resourceConfig = {
    income: {
        key: 'incomes',
        prefix: 'inc',
        title: 'Ingreso',
        create: 'createIncome',
        update: 'updateIncome',
        delete: 'deleteIncome',
        icon: BadgeDollarSign,
        fields: [
            { name: 'amount', label: 'Monto', type: 'number', step: '0.01', required: true },
            { name: 'source', label: 'Fuente', type: 'text', required: true },
            { name: 'status', label: 'Estado', type: 'select', options: ['confirmed', 'pending', 'cancelled'] },
            { name: 'date', label: 'Fecha', type: 'date', required: true },
            { name: 'note', label: 'Nota', type: 'textarea' },
        ],
        columns: [
            { key: 'source', label: 'Fuente' },
            { key: 'status', label: 'Estado', badge: true },
            { key: 'date', label: 'Fecha', date: true },
            { key: 'amount', label: 'Monto', money: true },
        ],
    },
    expense: {
        key: 'expenses',
        prefix: 'exp',
        title: 'Egreso',
        create: 'createExpense',
        update: 'updateExpense',
        delete: 'deleteExpense',
        icon: CreditCard,
        fields: [
            { name: 'amount', label: 'Monto', type: 'number', step: '0.01', required: true },
            { name: 'category', label: 'Categoría', type: 'category', required: true },
            { name: 'date', label: 'Fecha', type: 'date', required: true },
            { name: 'note', label: 'Nota', type: 'textarea' },
        ],
        columns: [
            { key: 'category', label: 'Categoría' },
            { key: 'note', label: 'Nota' },
            { key: 'date', label: 'Fecha', date: true },
            { key: 'amount', label: 'Monto', money: true },
        ],
    },
    budget: {
        key: 'budgets',
        prefix: 'bud',
        title: 'Presupuesto',
        create: 'createBudget',
        update: 'updateBudget',
        delete: 'deleteBudget',
        fields: [
            { name: 'name', label: 'Nombre', type: 'text', required: true },
            { name: 'startDate', label: 'Inicio', type: 'date', required: true },
            { name: 'endDate', label: 'Fin', type: 'date', required: true },
            { name: 'status', label: 'Estado', type: 'select', options: ['active', 'draft', 'archived'] },
            { name: 'currency', label: 'Moneda', type: 'text', required: true },
            { name: 'expenseToIncomeAlertThreshold', label: 'Alerta egreso/ingreso', type: 'number', step: '0.01' },
        ],
    },
    categoryBudget: {
        key: 'categoryBudgets',
        prefix: 'cb',
        title: 'Presupuesto por categoría',
        create: 'createCategoryBudget',
        update: 'updateCategoryBudget',
        delete: 'deleteCategoryBudget',
        fields: [
            { name: 'budgetId', label: 'Periodo', type: 'budget', required: true },
            { name: 'category', label: 'Categoría', type: 'category', required: true },
            { name: 'limitAmount', label: 'Límite', type: 'number', step: '0.01', required: true },
            { name: 'alertThreshold', label: 'Umbral de alerta', type: 'number', step: '0.01' },
        ],
    },
    category: {
        key: 'categories',
        prefix: 'cat',
        title: 'Categoría',
        create: 'createCategory',
        delete: 'deleteCategory',
        fields: [{ name: 'name', label: 'Nombre', type: 'text', required: true }],
    },
}
